### ISSUE TITLE
New Pictures!

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/gym-duckietown#107]
I think its time to add some new pictures! 

Some candidates:
![simplesim_free](https://user-images.githubusercontent.com/10503729/47261436-62f55780-d49d-11e8-951b-b4092b7f9777.png)
![screenshot from 2018-08-23 11-38-30](https://user-images.githubusercontent.com/10503729/47261437-638dee00-d49d-11e8-9ed9-68c9832f692e.png)
![pedestrians](https://user-images.githubusercontent.com/10503729/47261438-638dee00-d49d-11e8-8f6c-0b84037ebad2.gif)
![screenshot from 2018-08-23 11-38-45](https://user-images.githubusercontent.com/10503729/47261439-638dee00-d49d-11e8-8543-d3c0e98c5d11.png)

Maybe one of the distortion too?

**Comment by nithin127** [comment]
These look awesome!
