### ISSUE TITLE
Navigate by following a given route so the function closest_curve_point is clearly defined

### ISSUE THREAD

**Issue by jrabary** [duckietown/gym-duckietown#110]
The function `closest_curve_point` doesn't give a unique solution when the tile has many possible paths (for example in an intersection). 
A workaround is to limite the number of path, this is probably the case when you want to navigate from a point A to B with a fixed route. How can we add this kind of constraint to the environment ?

**Comment by bhairavmehta95** [comment]
Fixed in latest PRs
