### ISSUE TITLE
Cannot solve environment.yaml on conda

### ISSUE THREAD

**Issue by catmasteryip** [duckietown/gym-duckietown#111]
```
(base) C:\Users\Fujits\gym-duckietown>conda env create -f environment.yaml
Solving environment: failed

ResolvePackageNotFound:
  - pytorch=0.3
  - torchvision
```

![image](https://user-images.githubusercontent.com/29121012/47613956-e680fb00-dad2-11e8-9af4-09b6c2d18260.png)

I have pytorch 0.4 and pytorch-cpu 0.4 on anaconda, why cant the anaconda prompt resolve the environment? or does it need specifically pytorch 0.3?

**Comment by maximecb** [comment]
It should work with pytorch 0.4, but it will print a deprecation warning for some function calls.

**Comment by catmasteryip** [comment]
The problem is resolved (temporarily) by commenting the corresponding package requirements in .yaml. But I am not sure if this bypass would back fire later.

**Comment by liampaull** [comment]
can we close this?
