### ISSUE TITLE
Future of gym-duckietown

### ISSUE THREAD

**Issue by AI-Guru** [duckietown/gym-duckietown#127]
Namaste!

After some heavy experimentation, I strongly believe that gym-duckietown is an excellent environment for research and training. I see that it is definitely a building block when it comes to autonomous driving. It is significant.

Commits seem to be less frequent. And still, I see a huge potential for extensions. There is so much that could be done. 

I wonder: What is the current plan? Are you interested in cooperating to extend this excellent environment?

**Comment by liampaull** [comment]
Hi - thanks for the note - commits have become less frequent after the first instantiation of the AI driving Olympics, but will ramp up again as we prepare for V2 at ICRA 2019. We are always looking for collaborators though. Please let us know what extensions you would be interested in.

**Comment by bhairavmehta95** [comment]
HI @AI-Guru - thank you for your recommendations.

As Liam said, commits have obviously slowed down (many of us are students, and we took a few months working on some other research). But will actually start up again next week, as we start to devote more time to the second iteration of the competition.

In fact, both recommendations are actually already on the docket (#1 and #2 are actually both done - for #2 especially, this will become more relevant as we enable some developer-only features such as the NavigationTask in Duckietown).

In addition, this repository hasn't been nearly as closely monitored as it should (I apologize - I am still trying to figure out how to get notifications for this) but most things will change starting next week :)
