### ISSUE TITLE
Exercises, French Instructions

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/gym-duckietown#132]
https://github.com/duckietown/gym-duckietown/blob/master/exercises/basic_control.py

Anything that's in `master`, IMO, should also probably have accompanying English instructions?

@liampaull ^ you're the authority on this, so it's your call.

In addition, I will be building a `launch_env` helper function (as I have with the `learning` tutorials), because many of our examples are initializing the Simulator / DuckietownEnv differently.

**Comment by liampaull** [comment]
agree - I will work on English instructions and put them in the book

**Comment by bhairavmehta95** [comment]
Done.
