### ISSUE TITLE
No module named 'gym-duckietown'

### ISSUE THREAD

**Issue by rhshi** [duckietown/gym-duckietown#139]
As in issue #138, when I follow the proposed solution, I get `ModuleNotFoundError: No module named 'gym_duckietown'`

**Comment by prabhasak** [comment]
Hi. This error seems to be specific to Windows. I followed suggestions on [adding `PYTHONPATH`](https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages), but that didn't help either (The learning algorithms are running perfectly on Ubuntu and Mac). Can someone help me with this? Thanks!
