### ISSUE TITLE
Obstacles not moving

### ISSUE THREAD

**Issue by tejank10** [duckietown/gym-duckietown#143]
Hello! I tried running `manual_control.py` with `Duckietown-loop_pedestrians-v0`, but the obstacles were not moving. How do I fix this behavior?

**Comment by liampaull** [comment]
Sorry for the delay - I think @bhairavmehta95 is the one who might know the answer

**Comment by bhairavmehta95** [comment]
Running something like:

`python manual_control.py --env-name=Duckietown-loop_pedestrians-v0 --map-name=loop_pedestrians` 

works.

You have to make sure the map specified has pedestrian duckies with `static` set to `False` in the `.yaml` file.

**Comment by zhaoworking** [comment]
> Running something like:
> 
> `python manual_control.py --env-name=Duckietown-loop_pedestrians-v0 --map-name=loop_pedestrians`
> 
> works.
> 
> You have to make sure the map specified has pedestrian duckies with `static` set to `False` in the `.yaml` file.

I have already done that according to what u said , but the duckie stll don't moves. How should i do next?

**Comment by zhaoworking** [comment]
> Running something like:
> 
> `python manual_control.py --env-name=Duckietown-loop_pedestrians-v0 --map-name=loop_pedestrians`
> 
> works.
> 
> You have to make sure the map specified has pedestrian duckies with `static` set to `False` in the `.yaml` file.

![image](https://user-images.githubusercontent.com/43924380/72660331-60b6db80-3a07-11ea-9ba3-2f96aee607dd.png)

**Comment by zhaoworking** [comment]
I have solved it.
