### ISSUE TITLE
geometry package breaks simulation

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/gym-duckietown#145]
Where is the `geometry` package to be installed from (`pip install geometry` seems to be a different package that installs something called `Geometry`), or where is the file that implements this?

https://github.com/duckietown/gym-duckietown/blob/aido2_lf_r1/gym_duckietown/simulator.py#L8

**Comment by AndreaCensi** [comment]
@bhairavmehta95 it's PyGeometry

Not sure how it worked so far without it. (I imagine it's pulled by other dependencies in the later dockerfiles).
