### ISSUE TITLE
Not compatible with python 3.5+ anymore

### ISSUE THREAD

**Issue by takeitallsource** [duckietown/gym-duckietown#148]
A newly added dependency `dataclasses` have rendered the simulator incompatible with any python version below 3.7.

```
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

In python 3.6, we can use `pip install dataclasses` as a workaround but I am not sure if this brings other compatibility issues.

**Comment by bhairavmehta95** [comment]
Took the easy way out on this way, fixed in aido2 branch

**Comment by AI-Guru** [comment]
Unfortunately dataclasses is back. Removing python 3.5 compatibility.

**Comment by liampaull** [comment]
@bhairavmehta95 should this issue be re-opened?

**Comment by bhairavmehta95** [comment]
I think with the dataclasses, we just need to say its Py3.6 only. It's all a bit too "integrated" to make everything backwards compatible (based on some of the other DT infrastructure stuff)

**Comment by AI-Guru** [comment]
It looks to me that dataclasses are used only once in the entire codebase. I would vote for keeping 3.5 compatibility.
