### ISSUE TITLE
No module name 'geometry'

### ISSUE THREAD

**Issue by takeitallsource** [duckietown/gym-duckietown#149]
```  File "gym-duckietown/gym_duckietown/simulator.py", line 8, in <module>
    import geometry
ModuleNotFoundError: No module named 'geometry'
```

Is this a new dependency that it is not listed either in `setup.py` or `requirements.txt`?

**Comment by takeitallsource** [comment]
@AndreaCensi is this `pip install PyGeometry` the correct reference to this missing library?

**Comment by BryannX** [comment]
Are you running it from the Docker shell?

**Comment by bhairavmehta95** [comment]
Fixed in `aido2` `requirements.txt`
