### ISSUE TITLE
Multi-Agent?

### ISSUE THREAD

**Issue by AI-Guru** [duckietown/gym-duckietown#153]
Namaste!

I strongly believe that this project is relevant and significant. Excellent work!

An idea. I see Multi-Agent Deep Reinforcement Learning growing as we speak. Would it be feasible to extend this project to that case? In its essence, it would be allowing for more than a single car. Multiple viewports. Multiple actions.

What do you think?

**Comment by liampaull** [comment]
I absolutely agree.

**Comment by bhairavmehta95** [comment]
Going to close this, we have no real development plans for this.
