### ISSUE TITLE
pytorch_rl missing?

### ISSUE THREAD

**Issue by AI-Guru** [duckietown/gym-duckietown#156]
Namaste!

I try to follow the instructions in the docker section. Looks very promising.

One thing: You mention a fork of the A2C agent to be at /pytorch_rl. This is a little confusing. Is there something missing in the documentation?

**Comment by bhairavmehta95** [comment]
Hi @AI-Guru - unfortunately, I haven't gotten the time to update the repo's readme. I can update it now, but the scripts for **both** imitation learning and reinforcement learning are in the `learning/` subfolder. I will keep this issue open until I update all the instructions.

**Comment by bhairavmehta95** [comment]
Pending PR #157 , closing.
