### ISSUE TITLE
Missing dataclasses and pygeometry libraries

### ISSUE THREAD

**Issue by maivincent** [duckietown/gym-duckietown#159]
On Ubuntu 18.04, using the **master** branch:
Following the installation instructions (both as standalone or through Conda),  
>./manual_control.py --env-name Duckietown-udem1-v0

gives:
```
File "/gym-duckietown/gym_duckietown/simulator.py", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```
This can be fixed manually in the container with : 
> pip install dataclasses

---------

Then comes the next error:

```
  File "/gym-duckietown/gym_duckietown/simulator.py", line 8, in <module>
    import geometry
ModuleNotFoundError: No module named 'geometry'
```

Which can be fixed manually in the container with:
> pip install pygeometry

Would be nice if it the libraries were automatically installed!

**Comment by bhairavmehta95** [comment]
Thanks @maivincent :)
