### ISSUE TITLE
In exercises/basic_control.py: 'DuckietownEnv' object has no attribute 'get_lane_pos'

### ISSUE THREAD

**Issue by maivincent** [duckietown/gym-duckietown#161]
As written in the title:

Running exerices/basic_control.py leads to :

`Traceback (most recent call last):
  File "basic_control.py", line 37, in <module>
    lane_pose = env.get_lane_pos(env.cur_pos, env.cur_angle)
AttributeError: 'DuckietownEnv' object has no attribute 'get_lane_pos'
`
From what I understood, it should be `get_lane_pos2` instead.

**Comment by maivincent** [comment]
I confirm that changing `get_lane_pos(...)` to `get_lane_pos2(...)` at line 37 works.

**Comment by bhairavmehta95** [comment]
Ok, thanks!
