### ISSUE TITLE
Tried Duckietown-loop_pedestrians-v0 but found no obstacles

### ISSUE THREAD

**Issue by nitinnat** [duckietown/gym-duckietown#166]
Hi,

First of all, this is awesome work. I had two questions which I hoped you could answer.

1. I was trying out the manual control option as described in the Usage section of the readme. However, no matter what env_name I provide, I get the same map in the simulator. I am not sure if I am doing something wrong, but when I try Duckietown-loop_pedestrians-v0, I see no moving obstacles, 

2. How would I go about adding another duckiebot in the environment?

I am using Python 3.6 on a Windows machine.

Thanks,
Nitin

**Comment by nitinnat** [comment]
Figured out that I had to set the map name as well as env name

**Comment by nitinnat** [comment]
Figured out that I had to set the map name as well as env name

**Comment by nitinnat** [comment]
Fixed the first one. It would help if someone could tell me how to add another agent.

**Comment by zhaoworking** [comment]
> Figured out that I had to set the map name as well as env name

I encounter this problem too.So,can u tell me how to set the map name as well as the env name?
