### ISSUE TITLE
Camera Extrinsic Calibration

### ISSUE THREAD

**Issue by badz41** [duckietown/gym-duckietown#197]
Good Day!

We implement C-11 and acquire these data. We would like to ask if this calibration is okay.
![Screenshot from 2020-02-09 23-02-48](https://user-images.githubusercontent.com/60834818/74098015-f3055780-4b4d-11ea-9b51-6ddb3f6f959a.png)

**Comment by bhairavmehta95** [comment]
Looks okay. For these types of issues, please open them at github.com/duckietown/Software, as this doesn't relate to the simultor.
