### ISSUE TITLE
Is there a way to draw trajectory of the bot?

### ISSUE THREAD

**Issue by AlexKaravaev** [duckietown/gym-duckietown#212]
Can I somehow draw the path of the robot, that he already had driven? 

It would be relly useful to see, how robot is going from the top down view(**https://imgur.com/a6Ay3fE**)

**Comment by liampaull** [comment]
There is a way - since if you look at the challenge logs you can see it: e.g. https://challenges.duckietown.org/v4/humans/submissions/5981
but I'm not sure how. Maybe @AndreaCensi knows.

**Comment by AlexKaravaev** [comment]
@liampaull I have ended just rewriting simulator code to render robot trajectory in top_down view mode in episode, because I was developing not for competition, but for research work.

Anyway, thank you for response, will close now.
