### ISSUE TITLE
Tree mesh in udem1 renders poorly

### ISSUE THREAD

**Issue by maximecb** [duckietown/gym-duckietown#30]
@bhairavmehta95 Since we've enabled lighting, the tree mesh in the `udem1` level looks terrible. I think it's something to do with the normals. I've tried using blender to recompute them, but that did not improve things.

You can view this level with:
`./manual_control.py --map-name udem1`

We should find a new tree mesh. Preferably low polygon (< 1500 faces). Preferably with no more than 1 texture. No texture could be ok, as the obj loader can now load vertex colors from obj files.

**Comment by bhairavmehta95** [comment]
Sure, looking for one now.
