### ISSUE TITLE
Traffic light mesh

### ISSUE THREAD

**Issue by maximecb** [duckietown/gym-duckietown#45]
We will eventually want to have traffic lights. For this, we probably need a custom model, because Duckietown uses special red and green traffic lights, no yellow. The model should be low poly (< 1000 polygons), in obj format, must have only triangular faces.

@liampaull can you link us an image of that a Duckietown traffic light should look like, for reference?

**Comment by abdelq** [comment]
The one I'm using on the Unity simulator comes from https://github.com/duckietown/duckietown-sim-server/tree/master/duckietown_gazebo/models/semaforo

**Comment by maximecb** [comment]
@abdelq What does it look like?

**Comment by abdelq** [comment]
@maximecb It's pretty basic. A cube with a small protruding circle on each side except the top and bottom, obviously.

**Comment by liampaull** [comment]
@tanij do you have a mesh or cad file for the new traffic lights?
