### ISSUE TITLE
draw_bbox=True + first person observation

### ISSUE THREAD

**Issue by rperezdattari** [duckietown/gym-duckietown#85]
Hello,

Is there a way to use the draw_bbox flag = True and at the same time obtain as observation the first person view of the duckiebot?

Thanks!

**Comment by bhairavmehta95** [comment]
`draw_bbox` was actually created as more of a debugging tool. 

Maybe #84 might be of interest.

**Comment by bhairavmehta95** [comment]
We'll keep track of this with inside the issue referenced above.
