### ISSUE TITLE
ImportError: Library "fontconfig" not found

### ISSUE THREAD

**Issue by AuthenticEshkinKot** [duckietown/gym-duckietown#88]
I installed Docker image "gym-duckietown" on two separate PC, with Gentoo and with Ubuntu 16.04 in VirtualBox. Installation steps:

1. Install Docker
2. docker pull duckietown/gym-duckietown
3. docker run -it duckietown/gym-duckietown bash

In image's bash I executed next commands:

1. Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &> xvfb.log &
2. export DISPLAY=:0
3. ./manual_control.py --env-name Duckietown-udem1-v0

The last command failed with message "ImportError: Library "fontconfig" not found."
Full log - https://pastebin.com/5S9V7QNF

**Comment by bhairavmehta95** [comment]
It seems that this might be the issue here?

https://unix.stackexchange.com/questions/330068/package-fontconfig-not-found-despite-having-installed-libfontconfig1-dev

Have you made sure that you can find `fontconfig.pc`?

**Comment by bhairavmehta95** [comment]
Please comment again if you seem to still have this issue, but I'll close it for now since it seems like it might be a unique system thing.

**Comment by BryannX** [comment]
I've tried the suggested approach and still cannot get it to work. The stack trace is similar stemming from pyglet. I looked up the libfontconfig1-dev path and indeed there is no fontconfig.pc file and unfortunately my docker shell doesn't find any packages when i try to install fontconfig or libfontconfig1-dev

**Comment by SzilvasiPeter** [comment]
Same here as @BryannX mentioned. I tried to install the package with `apt install libfontconfig1-dev` command but the package could not be found:
> Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libfontconfig1-dev
