### ISSUE TITLE
Velocities in simulation and real world do not seem to match

### ISSUE THREAD

**Issue by PanagiotisBountouris** [duckietown/gym-duckietown#90]
I trained a CNN in the simulation using angular and translational velocities, but when I implemented it in the real city I witnessed that I had to multiply the angular velocities by a factor = 4 in order to have similar behavior as in the simulation. Did you face such problem again in the past and do you know why this could happen? Have you compared the outcome of the same velocities (v, ω/omega) in the simulation and in real world in order to be sure that they match?

**Comment by AndreaCensi** [comment]
@PanagiotisBountouris sync up with @julian121266 - we might have found some divergences with the model. Also see discussion in #aido-simulator.

**Comment by maximecb** [comment]
@bhairavmehta95 do you have the time/bandwidth to take care of the open issues?

**Comment by bhairavmehta95** [comment]
Yup
Will take care of it.

**Comment by bhairavmehta95** [comment]
Tracking in #81.
